# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RZW8-lrLJ7_YVCQwqhnfERCXl68gV01O
"""

from tensorflow.keras.layers import Input, Dense, Conv2D, MaxPooling2D, Dropout, Flatten
from tensorflow.keras import Model

input_tensor = Input((784, ))
x_tensor = Dense(64, activation='relu', name='dl01')(input_tensor)
x_tensor = Dense(64, activation='relu', name='dl02')(x_tensor)
output_tensor = Dense(10, activation='softmax', name='output')(x_tensor)

model_s = Model(inputs=input_tensor, outputs=output_tensor)

model_s.summary(
)

input_tensor = Input((227,227,3))
x_tensor = Conv2D(filters=96, kernel_size=(11,11), strides=4, activation='relu', name='conv1')(input_tensor)
x_tensor = MaxPooling2D(pool_size=(3,3), strides=2, name='maxpool1')(x_tensor)
x_tensor = Conv2D(filters=256, kernel_size=(5,5), strides=1, activation='relu', name='conv2')(x_tensor)
x_tensor = MaxPooling2D(pool_size=(3,3), strides=2, name='maxpool2')(x_tensor)
x_tensor = Conv2D(filters=384, kernel_size=(3,3), strides=1, activation='relu', name='conv3')(x_tensor)
x_tensor = Conv2D(filters=384, kernel_size=(3,3), strides=1, activation='relu', name='conv4')(x_tensor)
x_tensor = Conv2D(filters=384, kernel_size=(3,3), strides=1, activation='relu', name='conv5')(x_tensor)
x_tensor = MaxPooling2D(pool_size=(3,3), strides=2, name='maxpool3')(x_tensor)
x_tensor = Dropout(rate=0.5, name='dropout1')(x_tensor)

x_tensor = Flatten(name='flat')(x_tensor)
x_tensor = Dense(4096, activation='relu', name='fully1')(x_tensor)
x_tensor = Dropout(rate=0.5, name='dropout2')(x_tensor)
x_tensor = Dense(4096, activation='relu', name='fully2')(x_tensor)

output_tensor = Dense(1000, activation='softmax', name='output')(x_tensor)

model_t = Model(inputs=input_tensor, outputs=output_tensor)

model_t.summary()